---
title: "No Title"
author: "Joshua Scriven"
# output: html_notebook
# editor_options: 
#   chunk_output_type: inline
editor_options: 
  chunk_output_type: console
---

```{r}
projname <- "qo_request_..."
data_dir <- "../data/" # location of main input data
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message=FALSE)
```

```{r custom_functions, include=FALSE}
source("https://raw.githubusercontent.com/joshuascriven/helper_functions/main/helper_functions.R")
```

```{r message=FALSE, warning=FALSE, include=FALSE}
packageloader(c(
  "AICcmodavg"
  ,"anytime"
  ,"broom"
  ,"dplyr"
  ,"english"
  ,"fastDummies"
  ,"ggcorrplot"
  ,"ggpubr"
  ,"gtools"
  ,"gtsummary"
  ,"Hmisc"
  ,"janitor"
  ,"jtools"
  ,"knitr"
  ,"lmtest"
  ,"lubridate"
  ,"odbc"
  ,"openxlsx"
  ,"pampe"
  ,"plm"
  ,"qualtRics"
  ,"RColorBrewer"
  ,"readxl"
  ,"reshape2"
  ,"sandwich"
  ,"scales"
  ,"stargazer"
  ,"stringr"
  ,"tidyverse"
  ,"tm"
  ,"wesanderson"
  ,"wordcloud"
  ,"wordcloud2"
  ))
# BiocManager::install("AnnotationDbi")
```

# Import common data
```{r message=FALSE, warning=FALSE, include=FALSE}
api_key <- read.table(filemaker("api_key","tsv"), header = TRUE)

# LOC CPI Data
qualtrics_api_credentials(
  api_key = getKey("qualtrics_api_key")
  , base_url = getKey("qualtrics_base_url")
  , install = TRUE,overwrite = T); readRenviron("~/.Renviron")

dat_cpi <- fetch_survey(
  surveyID = all_surveys() %>% filter(isActive == TRUE, grepl("Tool - Child Protective Investigations$",name)) %>% pull(id)
  , verbose = TRUE
  , force_request = TRUE)

# Smartsheet
con <- dbConnect(odbc::odbc()
                 , driver = "Smartsheet Live Data Connector"
                 , database = "smartsheets"
                 , uid = getKey("smartsheet_uid")
                 , pwd = getKey("smartsheet_pwd")
                 , timeout = 10)

# Conversion Tables
## LOC CPI Columns
tab_names_cpi <-getdb(con, "qualtrics_loc_cpi_rename_2022_04_24") %>% drop_na(name_new)

## Education Surveys
### Formsite Columns

### Smartsheet Columns

### Qualtrics Columns

## Admin Tables
tab_ents <- getdb(con, "entity_table") %>% filter(TX_COUNTY  == "Data Not Available")



```

# Project-specific data
```{r data, warning=FALSE, cache=TRUE, include=FALSE}
dat <- read.xlsx(filemaker("..","xlsx"))# set name of worksheet


```

# Backup orig import with row identifiers and rename according columns
```{r}
# rename columns using tab_names_cpi
data <- dat_cpi
data$rec_idn <- seq(1,nrow(data),1)

dictionary <- tibble::tibble(
  new = tab_names_cpi$name_new,
  old = tab_names_cpi$name_old
)

vars_found_in_dictionary <- intersect(names(data), unique(dictionary$old))
temp_dict <- dictionary %>%
  dplyr::filter(old %in% vars_found_in_dictionary) %>%
  tibble::deframe()
data <- data %>% dplyr::rename(!!temp_dict)

# create county data
temp <- data %>% select(matches("county_|rec_idn")) %>% 
  gather(type, county, -rec_idn) %>% 
  na.omit() %>% 
  select(-type) %>% 
  arrange(rec_idn) %>% 
  select(rec_idn,county)
data <- merge(data,temp, by="rec_idn")

# derive circuit variable from county, using dictionary
data$circuit <- stringr::str_replace_all(data$county, setNames(tab_ents$TX_CIRCUIT, tab_ents$TX_COUNTY))

                 # , `Full.Name.(Supervisor)`!="** VACANT POSITION **") #this is not applicable. The vacancies apply to the supervisor position

# There are multiple persons assigned to the same PSN6. Keep only the first.
data_bac <- data
```

